import { Layout } from "@/components/layout/Layout";

const Terms = () => {
  return (
    <Layout>
      <div className="pt-24 pb-16 lg:pt-32 lg:pb-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto">
            <h1 className="font-display text-3xl sm:text-4xl font-bold mb-8">Terms of Service</h1>
            <p className="text-muted-foreground mb-8">Last updated: February 1, 2026</p>

            <div className="prose dark:prose-invert max-w-none space-y-8">
              <section>
                <h2 className="font-display text-xl font-semibold mb-4">1. Acceptance of Terms</h2>
                <p className="text-muted-foreground leading-relaxed">
                  By accessing or using Task2Top, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
                </p>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">2. Description of Service</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Task2Top provides an AI-powered study planning platform that helps students create personalized study schedules, track progress, and improve study habits.
                </p>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">3. User Accounts</h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  To use certain features, you must create an account. You are responsible for:
                </p>
                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                  <li>Maintaining the confidentiality of your account credentials</li>
                  <li>All activities that occur under your account</li>
                  <li>Notifying us immediately of any unauthorized use</li>
                </ul>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">4. Acceptable Use</h2>
                <p className="text-muted-foreground leading-relaxed mb-4">You agree not to:</p>
                <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                  <li>Use the service for any illegal purpose</li>
                  <li>Attempt to gain unauthorized access to our systems</li>
                  <li>Interfere with or disrupt the service</li>
                  <li>Share your account with others</li>
                  <li>Use automated systems to access the service without permission</li>
                </ul>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">5. Intellectual Property</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Task2Top and its content, features, and functionality are owned by us and are protected by copyright, trademark, and other intellectual property laws. Your study data and schedules remain yours.
                </p>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">6. AI-Generated Content</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Study schedules generated by our AI are suggestions based on your inputs. While we strive for accuracy, we do not guarantee that AI-generated schedules will be optimal for your specific needs. You are responsible for reviewing and adjusting schedules as needed.
                </p>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">7. Limitation of Liability</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Task2Top is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, special, or consequential damages arising from your use of the service.
                </p>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">8. Changes to Terms</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We may modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.
                </p>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">9. Termination</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We may terminate or suspend your account at our discretion for violations of these terms. You may delete your account at any time from your account settings.
                </p>
              </section>

              <section>
                <h2 className="font-display text-xl font-semibold mb-4">10. Contact</h2>
                <p className="text-muted-foreground leading-relaxed">
                  For questions about these Terms, contact us at:
                </p>
                <p className="text-muted-foreground mt-2">
                  <strong>Email:</strong> legal@task2top.com
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Terms;
